"""tests/integration/test_bundle_export_roundtrip.py — Round-trip test: export → validate → mock import.

Verifies that a ZIP generated by ExportService passes BundleManager validation
and can be processed by ImportService without rejection.
"""

from __future__ import annotations

import io
import zipfile
from unittest.mock import MagicMock, patch

from src.services.bundle_manager import BundleManager
from src.services.bundle_schemas import (
    AgentExportItem,
    BundleRPCResult,
    ExportBundleRequest,
    SkillExportItem,
)
from src.services.export_service import ExportService
from src.services.import_service import ImportService


class TestExportImportRoundtrip:
    """Round-trip: export ZIP → BundleManager validation → mock ImportService."""

    def test_export_then_process_zip(self):
        """ExportService ZIP passes BundleManager.process_zip() validation."""
        org_id = "test-roundtrip-org"

        payload = ExportBundleRequest(
            bundle_name="roundtrip-bundle",
            agents=[
                AgentExportItem(
                    role="analyst",
                    soul_json={
                        "role": "Analyst",
                        "goal": "Analyze complex data sets to extract insights",
                        "backstory": "A senior data analyst with expertise in statistics",
                    },
                    allowed_tools=["search", "read_file"],
                    max_iter=5,
                ),
                AgentExportItem(
                    role="reviewer",
                    soul_json={
                        "role": "Reviewer",
                        "goal": "Review all outputs for quality and accuracy",
                        "backstory": "A meticulous reviewer with strong attention to detail",
                    },
                    allowed_tools=["read_file"],
                    max_iter=3,
                ),
            ],
            skills=[
                SkillExportItem(
                    name="data_formatter",
                    code="def format_data(data):\n    return str(data)\n",
                ),
            ],
        )

        service = ExportService(org_id=org_id)
        zip_bytes, filename = service.export(payload)

        assert filename == "roundtrip-bundle.zip"
        assert len(zip_bytes) > 0

        # Verify the exported ZIP can be processed by BundleManager
        manager = BundleManager(org_id=org_id)
        content = manager.process_zip(zip_bytes)

        # Assert content structure
        assert content.manifest.bundle_info is not None
        assert content.manifest.bundle_info.name == "roundtrip-bundle"
        assert len(content.agents) == 2
        assert len(content.skills) == 1
        assert "data_formatter.py" in content.skills

        # Verify agent roles
        agent_roles = [a["role"] for a in content.agents]
        assert "analyst" in agent_roles
        assert "reviewer" in agent_roles

    def test_export_then_mock_import(self):
        """Round-trip: export → mock import via ImportService returns success."""
        org_id = "test-roundtrip-mock"

        payload = ExportBundleRequest(
            bundle_name="mock-roundtrip",
            agents=[
                AgentExportItem(
                    role="qa_agent",
                    soul_json={
                        "role": "QA Agent",
                        "goal": "Test applications thoroughly for quality assurance",
                        "backstory": "A quality assurance engineer with testing expertise",
                    },
                    allowed_tools=["search"],
                    max_iter=5,
                ),
            ],
        )

        service = ExportService(org_id=org_id)
        zip_bytes, _filename = service.export(payload)

        # Mock DB for ImportService
        mock_db = MagicMock()
        rpc_chain = MagicMock()
        rpc_chain.execute.return_value = MagicMock(
            data=BundleRPCResult(
                status="committed",
                bundle_id="mock-bundle-id",
                agents_count=1,
                flows_count=0,
                skills_count=0,
            ).model_dump()
        )
        mock_db.rpc.return_value = rpc_chain

        cm = MagicMock()
        cm.__enter__.return_value = mock_db
        cm.__exit__.return_value = False

        with (
            patch("src.services.import_service.get_tenant_client", return_value=cm),
            patch(
                "src.services.import_service.ImportService._check_version_guard",
                return_value=None,
            ),
            patch(
                "src.services.import_service.ImportService._register_skills",
                return_value=None,
            ),
            patch(
                "src.services.import_service.ImportService._register_flows",
                return_value=None,
            ),
        ):
            import_service = ImportService(org_id=org_id)
            result = import_service.process_bundle(zip_bytes)

            assert result.status == "committed"
            assert result.bundle_id == "mock-bundle-id"
            assert result.agents_count == 1

    def test_export_zip_has_correct_structure(self):
        """Exported ZIP has standard bundle-schema-v2 structure."""
        org_id = "test-structure-org"

        payload = ExportBundleRequest(
            agents=[
                AgentExportItem(
                    role="struct_agent",
                    soul_json={"goal": "Validate structure thoroughly",
                               "backstory": "A structural validator agent"},
                ),
            ],
        )

        service = ExportService(org_id=org_id)
        zip_bytes, _ = service.export(payload)

        with zipfile.ZipFile(io.BytesIO(zip_bytes)) as z:
            names = z.namelist()
            assert "manifest.json" in names, "Missing manifest.json"
            assert any(n.startswith("agents/") and n.endswith(".json") for n in names), \
                "Missing agents/*.json"

            # Verify manifest.json has required fields
            import json

            manifest = json.loads(z.read("manifest.json"))
            assert manifest["version"] == "2.0"
            assert "bundle_info" in manifest
            assert "hashes" in manifest
            assert len(manifest["hashes"]) > 0, "Hashes must be populated"

            # Every file in hashes must exist in ZIP
            for path in manifest["hashes"]:
                assert path in names, f"Hash references {path} but file not in ZIP"
