import asyncio
import os
import sys
from pathlib import Path

# Add root directory to path
root_dir = Path(__file__).parent.parent
sys.path.append(str(root_dir))

# Ensure we use the .env variables
from dotenv import load_dotenv
load_dotenv(dotenv_path=root_dir / ".env")

from src.flows.architect_flow import ArchitectFlow

async def main():
    # Use the org_id we found in the database
    org_id = "01b3cd88-7e73-48f1-8172-4e0f7b23ccef"
    user_id = None 
    
    print(f"--- Starting Agent Generation Test ---")
    print(f"Target Org: {org_id}")
    
    flow = ArchitectFlow(org_id=org_id, user_id=user_id)
    
    input_data = {
        "description": "Create a simple expert agent called 'Researcher' that can search for info and summarize it.",
        "bundle_name": "research-test-bundle",
        "doc_description": "Test bundle generated by ArchitectFlow"
    }
    
    print(f"Executing ArchitectFlow with description: {input_data['description']}")
    
    try:
        # We use execute() to trigger the full lifecycle (validation, task record, crew run, persistence)
        state = await flow.execute(input_data)
        
        print(f"\n--- Flow Result ---")
        print(f"Status: {state.status}")
        
        if state.status == "completed":
            print(f"SUCCESS: Agent generated and imported.")
            result = state.output_data
            print(f"Bundle ID: {result.get('bundle_id')}")
            print(f"Total Agents: {len(result.get('agents', []))}")
            print(f"Total Skills: {len(result.get('skills', []))}")
        else:
            print(f"FAILURE: Flow finished with status {state.status}")
            print(f"Error: {state.error}")
            
    except Exception as e:
        print(f"CRASH: Test failed with exception: {e}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    asyncio.run(main())
